In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Uefa Euro Cup Participated Teams General Statistics.csv')

In [3]:
df

,Rank,Team,Participations,Played,Win,Draw,Loss,Goal_For,Goal_Against,Goal_Difference,Points,Points/match
0,1,Germany,12,49,26,12,11,72,48,24,90,1.84
1,2,France,9,39,20,9,10,62,44,18,69,1.77
2,3,Spain,10,40,19,11,10,55,36,19,68,1.70
3,4,Italy,9,38,16,16,6,39,27,12,64,1.68
4,5,Portugal,7,35,18,9,8,49,31,18,63,1.80
5,6,Netherlands,9,35,17,8,10,57,37,20,59,1.69
6,7,Czech Republic,9,32,13,6,13,42,43,−1,45,1.41
7,8,Russia,11,33,12,7,14,38,45,−7,43,1.30
8,9,England,9,31,10,11,10,40,35,5,41,1.32
9,10,Croatia,5,18,8,5,5,23,20,3,29,1.61
10,11,Denmark,8,27,7,6,14,30,43,−13,27,1.00
11,12,Belgium,5,17,7,2,8,22,25,−3,23,1.35
12,13,Sweden,6,20,5,6,9,25,24,1,21,1.05
13,14,Greece,4,16,5,3,8,14,20,−6,18,1.13
14,15,Turkey,4,15,4,2,9,13,22,−9,14,0.93
15,16,Wales,1,6,4,0,2,10,6,4,12,2.00
16,17,Poland,3,11,2,6,3,7,9,−2,12,1.09
17,18,Switzerland,4,13,2,5,6,8,15,−7,11,0.85
18,19,Serbia,5,14,3,2,9,22,39,−17,11,0.79
19,20,Iceland,1,5,2,2,1,8,9,−1,8,1.60
20,21,Hungary,3,8,2,2,4,11,14,−3,8,1.00
21,22,Republic of Ireland,3,10,2,2,6,6,17,−11,8,0.80
22,23,Romania,5,16,1,5,10,10,21,−11,8,0.50
23,24,Scotland,2,6,2,1,3,4,5,−1,7,1.17
24,25,Norway,1,3,1,1,1,1,1,0,4,1.33
25,26,Slovakia,1,4,1,1,2,3,6,−3,4,1.00
26,27,Bulgaria,2,6,1,1,4,4,13,−9,4,0.67
27,28,Albania,1,3,1,0,2,1,3,−2,3,1.00
28,29,Northern Ireland,1,4,1,0,3,2,3,−1,3,0.75
29,30,Ukraine,2,6,1,0,5,2,9,−7,3,0.50
30,31,Slovenia,1,3,0,2,1,4,5,−1,2,0.67
31,32,Austria,2,6,0,2,4,2,7,−5,2,0.33
32,33,Latvia,1,3,0,1,2,1,5,−4,1,0.33

In [4]:
print(df.columns)

Index(['Rank', 'Team', 'Participations', 'Played', 'Win', 'Draw', 'Loss',
       'Goal_For', 'Goal_Against', 'Goal_Difference', 'Points',
       'Points/match'],
      dtype='object')

In [5]:
from scipy.spatial import distance
from scipy.spatial.distance import cityblock, euclidean
from sklearn.metrics.pairwise import cosine_similarity

In [8]:
man_Dist = distance.cityblock(df['Goal_For'].astype(float), df['Goal_Against'].astype(float))
euc_Dist = distance.euclidean(df['Goal_For'].astype(float), df['Goal_Against'].astype(float))

In [11]:
print('\t\t', 'Manhattan', '\t', 'Euclidean')
print('GF - GA', '\t' ,man_Dist, '\t\t' ,euc_Dist)

		 Manhattan 	 Euclidean
GF - GA 	 248.0 		 57.497826045860194

In [12]:
print(cosine_similarity([df.Goal_For], [df.Goal_Against]))

[[0.94172526]]